eeg:
  n_channels: 8
  channel_names:
  - P3
  - P7
  - PO7
  - PO4
  - PO3
  - PO8
  - P8
  - P4
  ref_channel_name: Pz
impedance:
  n_channels: 8
ui:
  channel_selection:
    n_channels: 8
    channel_names:
    - P3
    - P7
    - PO7
    - PO4
    - PO3
    - PO8
    - P8
    - P4
    ref_channel_name: Pz